#!/usr/bin/env bash
# This script uses a for loop to print the sting "Best School" 10 times
i=0
while ((i <= 12 )); do
    echo "Hour: $i"
    j=1
    while ((j <= 59)); do
        echo "$j"
        ((j++))
    done
    ((i++))
done
